[build]
  command = "bundle install && bundle exec jekyll build"

[build.environment]
  RUBY_VERSION = "3.1.0"

[build.dependencies]
  # Example: Installing build tools
  install = "apt-get install -y build-essential libpq-dev"
